# netlify.toml

[build]
command = "hugo --gc --minify"
publish = 'public'

[build.environment]
HUGO_VERSION = '0.147.2'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
